name: TriageBot
description: Automatically classify GitHub issues and request missing information using an LLM.
author: DaemonShip

branding:
  icon: tag
  color: blue

inputs:
  github-token:
    description: GitHub token with issues write permission (use secrets.GITHUB_TOKEN)
    required: true
  openai-api-key:
    description: API key for the LLM provider (OpenAI or any OpenAI-compatible API)
    required: true
  base-url:
    description: Optional base URL for an OpenAI-compatible API (e.g. Gemini, DeepSeek)
    required: false
  model:
    description: Model name to use for classification (default gpt-4o-mini)
    required: false
    default: gpt-4o-mini
  config-path:
    description: Path to triagebot config file (relative to repo root)
    required: false
    default: .github/triagebot.yml

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install TriageBot
      run: pip install -e ${{ github.action_path }} --quiet
      shell: bash
    - name: Run TriageBot
      run: python -m triagebot
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        OPENAI_BASE_URL: ${{ inputs.base-url }}
        OPENAI_MODEL: ${{ inputs.model }}
        TRIAGEBOT_CONFIG_PATH: ${{ inputs.config-path }}
